name: Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -G "Visual Studio 16 2019" -B ${{github.workspace}}/build 
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
