name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -G "Visual Studio 16 2019" -B ${{github.workspace}}/build 
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release
      - name: Pack
        working-directory: ${{github.workspace}}/build
        run: cpack -G "NSIS"
      - name: Publish
        working-directory: ${{github.workspace}}/build
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: photo_video_renamer-0.1.1-win64.exe
