name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Conan
        run: pip install conan
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -G "Visual Studio 16 2019" -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        working-directory: build
        run: ctest -C Release -V
      - name: Pack
        working-directory: build
        run: cpack -G "NSIS"
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: build/*.exe
