name: Checkout, configure and build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checkout-configure-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake -G "Visual Studio 16 2019" -B ${{github.workspace}}/build 
      - run: cmake --build ${{github.workspace}}/build --config Release
