name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        clangFormatVersion: 13
  build:
    needs: clang-format
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Conan
        run: pip install conan==1.55.0
      - name: Install packages
        run: conan install . --install-folder build --build missing --settings compiler=msvc --settings compiler.cppstd=17 --settings compiler.runtime=dynamic --settings compiler.version=193 --settings build_type=Release
      - name: Configure
        run: cmake -G "Visual Studio 17 2022" -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        working-directory: build
        run: ctest -C Release -V
      - name: Install EnVar plug-in for NSIS
        run: Invoke-WebRequest -Uri https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -OutFile EnVar_plugin.zip; 7z x EnVar_plugin.zip -o"C:\Program Files (x86)\NSIS"
      - name: Pack
        working-directory: build
        run: cpack -G "NSIS"
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          path: build/photo_video_renamer*.exe
