name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.13
      with:
        clangFormatVersion: 13
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04]
        include:
          - os: windows-2022
            compiler: msvc
            cmakePreset: conan-default
            cpackGenerator: NSIS
            publishExtension: exe
          - os: ubuntu-22.04
            compiler: gcc
            cmakePreset: conan-release
            cpackGenerator: DEB
            publishExtension: deb
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Conan
        run: pip install conan==2.0.7
      - name: Configure Conan
        run: conan profile detect
      - name: Install Conan packages
        run: conan install . --output-folder=build --build=missing --settings compiler=${{ matrix.compiler }} --settings compiler.cppstd=17 --settings build_type=Release
      - name: Configure
        run: cmake --preset ${{ matrix.cmakePreset }} -DCPACK_PACKAGE_CONTACT="${{ secrets.CONTACT }}"
      - name: Build
        run: cmake --build --preset conan-release
      - name: Test
        working-directory: build
        run: ctest --verbose --preset conan-release
      - name: Install EnVar plug-in for NSIS
        run: Invoke-WebRequest -Uri https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip -OutFile EnVar_plugin.zip; 7z x EnVar_plugin.zip -o"C:\Program Files (x86)\NSIS"
        if: runner.os == 'Windows'
      - name: Pack
        working-directory: build
        run: cpack -G "${{ matrix.cpackGenerator }}"
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: build/photo_video_renamer*.${{ matrix.publishExtension }}
